version: '3'

services:
  mysql:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_music
      MYSQL_HOST: 127.0.0.1
    volumes:
      - mysql-data:/var/lib/mysql
      - ./table.sql:/docker-entrypoint-initdb.d/table.sql
    ports:
      - "3307:3306"
    restart: always  # Ensure MySQL container restarts if it fails

  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    restart: always  # Ensure app container restarts if it fails

volumes:
  mysql-data:
